apiVersion: v1
kind: Pod
metadata:
  name: webhook
  labels:
    serve: hook
spec:
  containers:
    - image: quay.io/mengzn/audit-example:1.0
      name: webhook
      command: ["./app"]
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  tolerations:
    - effect: NoSchedule
      operator: Exists