apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    serve: test
spec:
  containers:
    - image: golang:alpine3.11
      name: test
      command: ["/bin/sh"]
      args: ["-c", "tail -f /dev/null"]
      volumeMounts:
        - mountPath: /go
          name: volume
  nodeSelector:
    kubernetes.io/os: linux
    node-role.kubernetes.io/master: ""
  volumes:
    - name: volume
      hostPath:
        path: /home/ubuntu/go/src/audit-hook
        type: Directory
  tolerations:
    - effect: NoSchedule
      operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  labels:
    serve: test
  name: test
  namespace: default
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    serve: test
  sessionAffinity: None
  type: ClusterIP